quotes/urls.py
from django.urls import path

from quotes import views


app_name = "quotes"


urlpatterns = [
    path("create/", views.CreateQuoteView.as_view(), name="create"),
    path("<slug:pk>/", views.QuoteDetailView.as_view(), name="by_id"),
    path("edit/<slug:pk>/", views.EditQuoteView.as_view(), name="edit"),
    path("delete/<slug:pk>/", views.DeleteQuoteView.as_view(), name="delete"),
    path("<slug:pk>/reaction/<int:reaction>/", views.SetReactionView.as_view(), name="set_reaction"),
    path("<slug:pk>/favourite/", views.AddToFavouritesView.as_view(), name="favourite"),
]

rainblood_quotes/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView
from django.conf.urls.static import static
from django.conf import settings

from rainblood_quotes.sitemaps import StaticSitemap, QuoteSitemap, ProfileSitemap
from rainblood_quotes.views import HomepageView


sitemaps = {
    "static": StaticSitemap,
    "quotes": QuoteSitemap,
    "users": ProfileSitemap,
}

urlpatterns = [
    path("", HomepageView.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path("quotes/", include("quotes.urls")),
    path("users/", include("users.urls")),
    path("search/", include("search.urls")),
    path("robots.txt/", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path("favicon.ico/", RedirectView.as_view(url="/static/img/fav/favicon.ico", permanent=True)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.contrib.auth import views
from django.urls import path, reverse_lazy

import users.views
from users import forms

app_name = "users"

urlpatterns = [
    path(
        "login/",
        users.views.MessagedLoginView.as_view(form_class=forms.LoginForm,),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "password_change/",
        views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            success_url=reverse_lazy("users:password_change_done"),
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path("signup/", users.views.signup, name="signup"),
    path("profile/edit/", users.views.update_profile, name="profile_edit"),
    path("profiles/<username>/", users.views.WatchProfileView.as_view(), name="profile"),
    path("activate/<username>/", users.views.activate, name="activate"),
]

quotes/models.py
import re

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from django.utils.translation import gettext_lazy as _


def simplify(item: str) -> str:
    if not item:
        return item
    item = item.strip().lower()
    item = re.sub(r'\W', '', item)
    item = re.sub(r'\s+', ' ', item)
    new = item[0]
    for letter in item[1:]:
        if new[-1] != letter:
            new += letter
    return new


class Video(models.Model):
    youtube_id = models.CharField(max_length=50)
    title = models.CharField(max_length=100)
    preview = models.ImageField(upload_to='uploads/videos/')

    class Meta:
        verbose_name = "Видео"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class QuoteObjectManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().prefetch_related("rate").annotate(rating=models.Sum("rate__value", default=0))


class Quote(models.Model):
    objects = QuoteObjectManager()
    title = models.CharField(max_length=100, verbose_name="заголовок")
    full_text = models.TextField(verbose_name="полный текст", max_length=1000)
    time = models.PositiveIntegerField(verbose_name="временная метка")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='quotes', verbose_name="автор")
    video = models.ForeignKey(Video, on_delete=models.CASCADE, related_name='quotes', verbose_name="видео")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    search_string = models.TextField(verbose_name="строка поиска")

    def full_clean(self, *args, **kwargs):
        self.search_string = simplify(self.title + " " + self.full_text)
        super().full_clean(*args, **kwargs)

    def save(self, *args, **kwargs):
        if not self.search_string:
            self.full_clean()
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("quotes:by_id", args=(self.id,))

    class Meta:
        ordering = ("-id",)
        verbose_name = "Цитата"
        verbose_name_plural = "Цитаты"

    def __str__(self):
        return self.title


class Rate(models.Model):
    class Values(models.IntegerChoices):
        like = 1, _("like")
        dislike = -1, _("dislike")

    quote = models.ForeignKey(Quote, on_delete=models.CASCADE, related_name="rate")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="rate")
    value = models.IntegerField(choices=Values.choices, verbose_name="оценка")

    class Meta:
        verbose_name = "рейтинг"
        verbose_name_plural = "рейтинги"
        unique_together = ('quote', 'user')

    def __str__(self):
        return f"{self.quote} - {self.user} - {self.value}"

quotes/forms.py
from django.forms import ModelForm, TimeField, TimeInput
from django.utils.translation import gettext

from quotes.models import Quote


class QuoteForm(ModelForm):
    time = TimeField(label=gettext("time"), widget=TimeInput(attrs={'type': 'time'}))

    class Meta:
        model = Quote
        exclude = ['author', 'time', 'search_string']

quotes/views.py
import datetime

from django.core.exceptions import PermissionDenied, BadRequest
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.utils.translation import gettext as _
from django.views.generic import DetailView, FormView, UpdateView, DeleteView, View

from quotes.forms import QuoteForm
from quotes.models import Quote, Rate


def to_seconds(time: datetime.time):
    return time.hour * 60 + time.minute


def from_seconds(time: int):
    return datetime.time(hour=time // 60, minute=time % 60)


class CreateQuoteView(FormView, LoginRequiredMixin):
    model = Quote
    form_class = QuoteForm
    template_name = "quotes/create.html"
    success_url = reverse_lazy("index")

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            obj = self.model.objects.create(author=self.request.user, video=form.cleaned_data['video'],
                                            title=form.cleaned_data['title'],
                                            full_text=form.cleaned_data['full_text'],
                                            time=to_seconds(form.cleaned_data['time']))
            self.success_url = reverse_lazy("quotes:by_id", args=[obj.id])
            messages.success(self.request, _("quote_created"))
        return super().post(request, *args, **kwargs)


class QuoteDetailView(DetailView):
    model = Quote
    template_name = "quotes/quote.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["my"] = self.get_object().author.pk == self.request.user.pk
        context["duration"] = from_seconds(self.get_object().time)
        context["reaction"] = Rate.objects.filter(quote=self.get_object(), user=self.request.user.id).first()
        return context


class EditQuoteView(LoginRequiredMixin, UpdateView):
    model = Quote
    form_class = QuoteForm
    template_name = "quotes/update.html"
    success_url = reverse_lazy("index")

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.author != self.request.user:
            raise PermissionDenied()
        return obj

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if hasattr(self, "object"):
            form.fields["time"].initial = from_seconds(self.object.time)
        return form

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            obj = self.get_object()
            obj.time = to_seconds(form.cleaned_data["time"])
            obj.save()
            self.success_url = reverse_lazy("quotes:by_id", args=[obj.id])
            messages.success(self.request, _("quote_updated"))
        return super().post(request, *args, **kwargs)


class DeleteQuoteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = Quote
    success_url = reverse_lazy("search:overview")
    template_name = "quotes/confirm_delete.html"
    success_message = _("quote_deleted")

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.author != self.request.user:
            raise PermissionDenied()
        return obj


class SetReactionView(LoginRequiredMixin, View):
    success_message = _("reaction_set")

    def post(self, request, *args, **kwargs):
        quote = get_object_or_404(Quote.objects.only("id"), pk=self.kwargs.get("pk"))
        rate = Rate.objects.filter(quote__id=kwargs["pk"], user=self.request.user).first()
        if self.kwargs.get("reaction") not in [0, 1]:
            raise BadRequest()
        value = Rate.Values.like if self.kwargs.get("reaction") == 1 else Rate.Values.dislike
        if rate:
            if rate.value == value:
                rate.delete()
                messages.success(self.request, _("reaction_removed"))
            else:
                rate.value = value
                rate.save()
                messages.success(self.request, _("reaction_set"))
        else:
            Rate.objects.create(quote=quote, value=value, user=self.request.user)
            messages.success(self.request, _("reaction_set"))
        return redirect(reverse("quotes:by_id", args=[quote.id]))


class AddToFavouritesView(SuccessMessageMixin, LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        quote = get_object_or_404(Quote.objects.only("id"), pk=self.kwargs.get("pk"))
        if quote not in request.user.profile.favourites.all():
            request.user.profile.favourites.add(quote)
            messages.success(self.request, _("fav_set"))
        else:
            request.user.profile.favourites.remove(quote)
            messages.success(self.request, _("fav_removed"))
        return redirect(reverse("quotes:by_id", args=[quote.id]))

templates/quotes/confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{% trans 'delete_quote_header' %}{% endblock %}
{% block content %}
    <div class="container align-content-center justify-content-center">
        <h2 class="py-3 text-center m-3">{% trans 'quote_delete_text' %}</h2>
        <form method="POST">
            {% csrf_token %}
            <div class="align-center">
                <img src="{% static 'img/korben.jpg' %}" alt="" class="align-center img-thumbnail rounded-5">
            </div>
            <div class="container mt-3">
                <button class="btn btn-primary mx-2" type="submit">{% trans 'b_delete_quote' %}</button>
                <a href="{% url 'quotes:by_id' pk=object.id %}" class="btn btn-secondary opacity-75" role="button">{% trans 'back' %}</a>
            </div>
        </form>
    </div>
{% endblock %}

templates/quotes/create.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'create_quote_header' %}{% endblock %}
{% block content %}
{% with header_text="create_quote_text" button_text="b_create_quote" %}
  {% include 'includes/form.html' %}
{% endwith %}
{% endblock %}

templates/quotes/quote.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% load i18n %}
{% block title %}{% trans 'view_quote_header' %} {{ object.title }}{% endblock %}
{% block content %}
    <h1 class="text-center">{% trans 'quote_overview' %}</h1>
    <div class="container mt-5">

        <div class="row">
            <div class="col">
                <iframe width="750px" height="500px" class="rounded-3"
                        src="https://www.youtube.com/embed/{{ quote.video.youtube_id }}?start={{ quote.time }}"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                        referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>

            <div class="col">
                <h3 class="">{{ quote.title|capfirst }}</h3>
                <p class="fs-5">{{ object.full_text|capfirst }}</p>
                {% if my %}
                    <a href="{% url 'quotes:edit' pk=object.pk %}" class="btn btn-light me-2"
                       role="button">{% trans 'edit_quote' %}</a>
                    <a href="{% url 'quotes:delete' pk=object.pk %}" class="btn btn-light me-2 opacity-75 "
                       role="button">{% trans 'delete_quote' %}</a>
                {% endif %}
                <div class="d-flex justify-content-start mt-3">
                    <form id="like-form" action="{% url 'quotes:set_reaction' pk=object.pk reaction=1 %}" method="post"
                          class="rounded-start" style="background-color: rgba(20, 20, 20, 0.5)">
                        <a href="" onclick="document.getElementById('like-form').submit(); return false;"
                           class="">
                            {% if reaction and reaction.value == reaction.Values.like %}
                                <img src="{% static 'img/like-active.svg' %}" alt="" width="50">
                            {% else %}
                                <img src="{% static 'img/like.svg' %}" alt="" width="50">
                            {% endif %}
                        </a>
                        {% csrf_token %}
                    </form>
                    <form id="dislike-form" action="{% url 'quotes:set_reaction' pk=object.pk reaction=0 %}"
                          method="post" style="background-color: rgba(20, 20, 20, 0.5)"
                          class="">
                        <a href="" onclick="document.getElementById('dislike-form').submit(); return false;"
                           class="">
                            {% if reaction and reaction.value == reaction.Values.dislike %}
                                <img src="{% static 'img/dislike-active.svg' %}" alt="" width="50">
                            {% else %}
                                <img src="{% static 'img/dislike.svg' %}" alt="" width="50">
                            {% endif %}
                        </a>
                        {% csrf_token %}
                    </form>
                    <form id="fav-form" action="{% url 'quotes:favourite' pk=object.pk %}"
                          method="post" style="background-color: rgba(20, 20, 20, 0.5)"
                          class="rounded-end">
                        <a href="" onclick="document.getElementById('fav-form').submit(); return false;"
                           class="">
                            {% if quote in user.profile.favourites.all %}
                                <img src="{% static 'img/favourite-active.svg' %}" alt="" width="50">
                            {% else %}
                                <img src="{% static 'img/favourite.svg' %}" alt="" width="50">
                            {% endif %}
                        </a>
                        {% csrf_token %}
                    </form>
                </div>
                <div class="mt-4">
                    <a href="{% url 'users:profile' username=quote.author.username %}" class="text-decoration-none text-reset">
                    <h4 class="">{% trans 'author' %}: {{ quote.author.username }}</h4>
                    {% if quote.author.profile.image %}
                        {% thumbnail quote.author.profile.image "150x150" crop="center" as im %}
                            <img src="{{ im.url }}" alt="..."
                                 class="img-fluid img-thumbnail mb-2"
                                 style="width: 150px; z-index: 1">
                        {% endthumbnail %}
                    {% else %}
                        <img src="{% static 'img/default_avatar.png' %}" alt="..."
                             class="img-fluid img-thumbnail mb-2"
                             style="width: 150px; z-index: 1">
                    {% endif %}
                    </a>
                </div>
            </div>

        </div>

    </div>
{% endblock %}

templates/quotes/update.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'update_quote_header' %}{% endblock %}
{% block content %}
{% with header_text="update_quote_text" button_text="b_update_quote" %}
  {% include 'includes/form.html' %}
{% endwith %}
{% endblock %}