quotes/urls.py
from django.urls import path

from quotes import views


app_name = "quotes"


urlpatterns = [
    path("create/", views.CreateQuoteView.as_view(), name="create"),
    path("<slug:pk>/", views.QuoteDetailView.as_view(), name="by_id"),
    path("edit/<slug:pk>/", views.EditQuoteView.as_view(), name="edit"),
    path("delete/<slug:pk>/", views.DeleteQuoteView.as_view(), name="delete"),
    path("<slug:pk>/reaction/<int:reaction>/", views.SetReactionView.as_view(), name="set_reaction"),
    path("<slug:pk>/favourite/", views.AddToFavouritesView.as_view(), name="favourite"),
]

rainblood_quotes/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView
from django.conf.urls.static import static
from django.conf import settings

from rainblood_quotes.sitemaps import StaticSitemap, QuoteSitemap, ProfileSitemap
from rainblood_quotes.views import HomepageView


sitemaps = {
    "static": StaticSitemap,
    "quotes": QuoteSitemap,
    "users": ProfileSitemap,
}

urlpatterns = [
    path("", HomepageView.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path("quotes/", include("quotes.urls")),
    path("users/", include("users.urls")),
    path("search/", include("search.urls")),
    path("robots.txt/", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path("favicon.ico/", RedirectView.as_view(url="/static/img/fav/favicon.ico", permanent=True)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

search/urls.py
from django.urls import path

from search.views import Overview, SearchView, FavView


app_name = "search"


urlpatterns = [
    path("overview/", Overview.as_view(), name="overview"),
    path("my_fav/", FavView.as_view(), name="my_fav"),
    path("", SearchView.as_view(), name="by"),
]

users/urls.py
from django.contrib.auth import views
from django.urls import path, reverse_lazy

import users.views
from users import forms

app_name = "users"

urlpatterns = [
    path(
        "login/",
        users.views.MessagedLoginView.as_view(form_class=forms.LoginForm,),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "password_change/",
        views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            success_url=reverse_lazy("users:password_change_done"),
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path("signup/", users.views.signup, name="signup"),
    path("profile/edit/", users.views.update_profile, name="profile_edit"),
    path("profiles/<username>/", users.views.WatchProfileView.as_view(), name="profile"),
    path("activate/<username>/", users.views.activate, name="activate"),
]

templates/includes/footer.html
{% load i18n %}
<footer class="mt-auto">
  <p class="text-center text-body-secondary">{% trans 'footer' %}</p>
</footer>

templates/includes/form.html
{% load crispy_forms_filters %}
{% load i18n %}
<div class="container">
	<h2 class="py-3 text-center m-3">{% trans header_text %}</h2>
	<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" type="submit">{% trans button_text %}</button>
  </form>
</div>

templates/includes/header.html
{% load i18n %}
{% load static %}
<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <nav class="navbar navbar-expand-lg rounded">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
            <img src="{% static 'img/logotype.jpg' %}" alt="logo" class="bi me-3 rounded" width="60" height="50">
        </a>
        <ul class="nav nav-pills">
            {% with request.resolver_match as rm%}
                <li class="nav-item"><a href="{% url 'index' %}"
                                        class="nav-link {% if rm.view_name == 'index' %}active{% endif %}">{% trans 'home' %}</a>
                </li>
                <li class="nav-item"><a href="{% url 'search:overview' %}"
                                        class="nav-link {% if rm.namespace == 'search' %}active{% endif %}">{% trans 'overview' %}</a>
                </li>
                {% if user.is_active %}
                    <li class="nav-item"><a href="{% url 'quotes:create' %}"
                                            class="nav-link {% if rm.namespace == 'quotes' %}active{% endif %}">{% trans 'create_quote' %}</a>
                    </li>
                    <li><a class="nav-link {% if rm.namespace == 'users' %}active{% endif %}"
                           href="{% url 'users:profile' username=user.username %}">{% trans 'profile' %}</a></li>
                {% endif %}
            {% endwith %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button"
                   aria-expanded="false">{% trans 'auth' %}</a>
                <ul class="dropdown-menu">
                    {% if not user.is_active %}
                        <li><a class="dropdown-item" href="{% url 'users:login' %}">{% trans 'login' %}</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:signup' %}">{% trans 'signup' %}</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:password_reset' %}">{% trans 'passreset' %}</a>
                        </li>
                    {% else %}
                        <form id="logout-form" action="{% url 'users:logout' %}" method="post" class="dropdown-item">
                            <a href="" onclick="document.getElementById('logout-form').submit(); return false;"
                               class="text-decoration-none text-reset">{% trans 'logout' %}</a>
                            {% csrf_token %}
                        </form>
                        <li><a class="dropdown-item"
                               href="{% url 'users:password_change' %}">{% trans 'passchange' %}</a></li>
                    {% endif %}
                </ul>
            </li>
            {% if user.is_superuser %}
                <li class="nav-item"><a href="{% url 'admin:index' %}" class="nav-link">{% trans 'admin' %}</a></li>
            {% endif %}
        </ul>
    </nav>
</header>

templates/includes/quotecard.html
{% load thumbnail %}
<a href="{% url 'quotes:by_id' pk=quote.id %}">
    <div class="col-auto align-center card card-inverse mx-2 position-relative">

        {% thumbnail quote.video.preview "640x480" crop="center" as im %}
            <img src="{{ im.url }}" alt="" width="100%" height="240"
                 class="bd-placeholder-img card-img-top rounded opacity-50">
        {% endthumbnail %}
        <div class="shadow-lg rounded-2"
             style="position: absolute; top: 45%; left: 1.25%; width: 97%; background-color: rgba(20, 20, 20, 0.9)">
            <h4 class="text-center">{{ quote.title|truncatechars:30 }}</h4>
        </div>
        <div class="d-flex justify-content-end"
             style="position: absolute; top: 85%; width: 100%">
            {% with quote.rating as rt %}
                <h5 class="pe-2"
                    style="color: {% if rt < 0 %} rgba(255,0,0,0.75) {% elif rt == 0 %} rgba(240,240,240,0.75) {% else %} #009600{% endif %}">
                    {% if rt > 0 %}+{% endif %}{{ rt }}</h5>
            {% endwith %}
        </div>
    </div>
</a>