rainblood_quotes/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView
from django.conf.urls.static import static
from django.conf import settings

from rainblood_quotes.sitemaps import StaticSitemap, QuoteSitemap, ProfileSitemap
from rainblood_quotes.views import HomepageView


sitemaps = {
    "static": StaticSitemap,
    "quotes": QuoteSitemap,
    "users": ProfileSitemap,
}

urlpatterns = [
    path("", HomepageView.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path("quotes/", include("quotes.urls")),
    path("users/", include("users.urls")),
    path("search/", include("search.urls")),
    path("robots.txt/", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path("favicon.ico/", RedirectView.as_view(url="/static/img/fav/favicon.ico", permanent=True)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

search/urls.py
from django.urls import path

from search.views import Overview, SearchView, FavView


app_name = "search"


urlpatterns = [
    path("overview/", Overview.as_view(), name="overview"),
    path("my_fav/", FavView.as_view(), name="my_fav"),
    path("", SearchView.as_view(), name="by"),
]

users/urls.py
from django.contrib.auth import views
from django.urls import path, reverse_lazy

import users.views
from users import forms

app_name = "users"

urlpatterns = [
    path(
        "login/",
        users.views.MessagedLoginView.as_view(form_class=forms.LoginForm,),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "password_change/",
        views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            success_url=reverse_lazy("users:password_change_done"),
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path("signup/", users.views.signup, name="signup"),
    path("profile/edit/", users.views.update_profile, name="profile_edit"),
    path("profiles/<username>/", users.views.WatchProfileView.as_view(), name="profile"),
    path("activate/<username>/", users.views.activate, name="activate"),
]

users/models.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User as DjangoUser
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from quotes.models import Quote

DjangoUser._meta.get_field('email')._unique = True


def max_size_validator(obj):
    print(obj.file.size )
    if obj and obj.file.size > settings.MAX_FILE_SIZE_MB * 1024 * 1024:
        raise ValidationError(f'{_("filesize_limit_increased")} ({settings.MAX_FILE_SIZE_MB} MB)')


class Profile(models.Model):
    user = models.OneToOneField(
        DjangoUser,
        on_delete=models.CASCADE,
        related_name="profile",
    )
    birthday = models.DateField(null=True, blank=True, verbose_name="день рождения",)
    about = models.TextField(verbose_name="обо мне", null=True, blank=True, max_length=1000)
    image = models.ImageField(
        upload_to="uploads/profile_pics/",
        null=True,
        blank=True,
        verbose_name="изображение профиля",
        validators=[max_size_validator],
    )
    favourites = models.ManyToManyField(Quote, blank=True, related_name="favourites", verbose_name="избранное")
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Профиль"
        ordering = ("-id",)

    def get_absolute_url(self):
        return reverse("users:profile", args=(self.user.username,))

users/forms.py
from datetime import datetime

from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, User, AuthenticationForm
from django.utils.translation import gettext_lazy as _

from users.models import Profile


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = _('email_or_username')


class SignUpForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].required = True

    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "password1",
            "password2",
        )


class UserUpdateForm(UserChangeForm):
    password = None

    class Meta(UserChangeForm.Meta):
        model = User
        fields = (
            "first_name",
            "last_name",
        )


class UpdateProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["birthday"].widget = forms.SelectDateWidget(
            years=range(1900, datetime.now().year + 1),
        )

    class Meta:
        model = Profile
        fields = (
            "birthday",
            "about",
            "image",
        )

users/views.py
from django.conf import settings
from django.http import HttpResponseNotFound
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.core.signing import TimestampSigner, BadSignature
from django.contrib import messages
from django.utils.translation import gettext
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import LoginView
from django.contrib.auth.signals import user_logged_out
from django.dispatch import receiver

from users.forms import SignUpForm, UpdateProfileForm, UserUpdateForm
from users.models import Profile


@receiver(user_logged_out)
def on_user_logged_out(sender, request, **kwargs):
    messages.add_message(request, messages.INFO, gettext("logout_success"))


class MessagedLoginView(SuccessMessageMixin, LoginView):
    template_name = 'users/login.html'
    success_url = reverse_lazy("index")
    success_message = gettext("login_success")


def signup(request):
    form = SignUpForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        instance = form.save()
        instance.is_active = False
        instance.save()
        Profile.objects.create(user=instance)
        token = TimestampSigner().sign(form.cleaned_data['username'])
        link = request.build_absolute_uri(reverse_lazy('users:activate', args=(token,)))
        send_mail(
            subject="Verification email",
            message=f"Welcome! For activate your account,"
                    f" go to:\n{link}",
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[form.cleaned_data["email"]],
        )
        messages.success(request, gettext("user_created"))
        return redirect(reverse("users:login"))
    return render(
        request,
        "users/signup.html",
        {"form": form},
    )


@login_required(login_url=reverse_lazy("users:login"))
def update_profile(request):
    if request.method == "POST":
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(
            request.POST,
            request.FILES,
            instance=request.user.profile,
        )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, gettext("profile_updated"))
            return redirect(reverse("users:profile_edit"))
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)

    return render(
        request,
        "users/profile.html",
        {"user_form": user_form, "profile_form": profile_form},
    )


def activate(request, username):
    try:
        username = TimestampSigner().unsign(username)
    except BadSignature:
        messages.error(request, gettext("bad_activate_link"))
        return redirect("index")
    user = User.objects.get(username=username)
    if user.is_active:
        messages.error(request, gettext("user_is_active"))
        return redirect("index")
    user.is_active = True
    messages.success(request, gettext("account_activated"))
    user.save()
    return redirect(reverse("users:login"))


class WatchProfileView(TemplateView):
    template_name = "users/user.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["profile"] = get_object_or_404(User.objects.select_related("profile"), username=self.kwargs["username"])
        if not context["profile"]:
            return HttpResponseNotFound()
        context["num_quotes"] = context["profile"].quotes.count()
        context["num_fav"] = context["profile"].profile.favourites.count()
        context["my"] = context["profile"].pk == self.request.user.pk
        context["quotes"] = context["profile"].quotes.all()[:4]
        return context

templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load i18n %}
{% block title %}{% trans 'login' %}{% endblock %}
{% block content %}
    <div class="container">
        <h2 class="py-3 text-center m-3">{% trans "login_text" %}</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-primary" type="submit">{% trans "login_button" %}</button>
            <a href="{% url 'users:password_reset' %}" class="btn btn-secondary m-2 opacity-75" role="button">{% trans 'forgot_password' %}</a>
        </form>
    </div>
{% endblock %}

templates/users/password_change.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'passchange' %}{% endblock %}
{% block content %}
{% with header_text="passchange_text" button_text="passchange_button" %}
  {% include 'includes/form.html' %}
{% endwith %}
{% endblock %}

templates/users/password_change_done.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'passchange_done' %}{% endblock %}
{% block content %}
<div class="container text-center">
  <h2>{% trans 'passchanged' %}</h2>
</div>
{% endblock %}

templates/users/password_reset.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'passreset' %}{% endblock %}
{% block content %}
{% with header_text="passreset_text" button_text="passreset_button" %}
  {% include 'includes/form.html' %}
{% endwith %}
{% endblock %}

templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'passreset_complete' %}{% endblock %}
{% block content %}
<div class="container text-center">
  <h2>{% trans 'passreseted' %}</h2>
</div>
{% endblock %}

templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'confirm_reset' %}{% endblock %}
{% block content %}
{% with header_text="confirm_reset_text" button_text="confirm_reset_button" %}
  {% include 'includes/form.html' %}
{% endwith %}
{% endblock %}

templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'passreset_done' %}{% endblock %}
{% block content %}
<div class="container text-center">
  <h1>{% trans 'passreset_done_text' %}</h1>
</div>
{% endblock %}

templates/users/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
(Your username: {{ user.username }})
{{ protocol}}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

templates/users/profile.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load i18n %}
{% block title %}{% trans 'profile_edit' %}{% endblock %}
{% block content %}
<div class="container">
	<h2 class="py-3">{% trans 'profile' %}</h2>
	<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form|crispy }}
    {{ profile_form|crispy }}
    <button class="btn btn-primary" type="submit">{% trans 'submit' %}</button>
  </form>
</div>
{% endblock %}

templates/users/signup.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load i18n %}
{% block title %}{% trans 'signup' %}{% endblock %}
{% block content %}
<div class="container">
	<h2 class="py-3 text-center m-3">{% trans 'signup_text' %}</h2>
	<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" type="submit">{% trans 'signup_button' %}</button>
  </form>
</div>
{% endblock %}

templates/users/user.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load thumbnail %}
{% block title %}{% trans 'profile_view' %} {{ profile.username }}{% endblock %}
{% block content %}
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center">
            <div class="col col-lg-9 col-xl-8">
                <div class="card">
                    <div class="rounded-top text-white d-flex flex-row "
                         style="background-image: url({% static 'img/bnr.png' %});">
                        <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px;">
                            {% if profile.profile.image %}
                                {% thumbnail profile.profile.image "150x150" crop="center" as im %}
                                    <img src="{{ im.url }}" alt="..."
                                         class="img-fluid img-thumbnail mt-4 mb-2"
                                         style="width: 150px; z-index: 1">
                                {% endthumbnail %}
                            {% else %}
                                <img src="{% static 'img/default_avatar.png' %}" alt="..."
                                     class="img-fluid img-thumbnail mt-4 mb-2"
                                     style="width: 150px; z-index: 1">
                            {% endif %}
                        </div>
                        <div class="ms-3"
                             style="margin-top: {% if profile.first_name or profile.last_name %}100px{% else %}130px{% endif %}">
                            <h5>{{ profile.username }}</h5>
                            <p>
                                {% if profile.first_name %}
                                    <span>{{ profile.first_name }} </span>
                                {% endif %}
                                {% if profile.last_name %}
                                    <span>{{ profile.last_name }} </span>
                                {% endif %}
                            </p>
                            {% if my %}
                                <div class="d-flex justify-content-around mt-auto">
                                    <a href="{% url 'search:my_fav' %}" class="btn btn-light me-2 opacity-75"
                                       role="button">{% trans 'b_favourites' %}</a>
                                    <a href="{% url 'users:profile_edit' %}" class="btn btn-dark me-2 "
                                       role="button">{% trans 'edit_profile' %}</a>
                                </div>
                            {% endif %}
                        </div>
                        <div class="d-flex text-center text-body align-self-end py-3 ms-auto">
                            <div>
                                <p class="mb-1 h5 text-white">{{ num_quotes }}</p>
                                <p class="small mb-0 text-white">{% trans 'quotes_created' %}</p>
                            </div>
                            <div class="px-3">
                                <p class="mb-1 h5 text-white">{{ num_fav }}</p>
                                <p class="small mb-0 text-white">{% trans 'favourites_plural' %}</p>
                            </div>
                        </div>
                    </div>

                    <div class="card-body p-4 text-black">
                        {% if profile.profile.birthday or profile.profile.about %}
                            <div class="mb-5  text-body">
                                <div class="p-4 bg-body-tertiary rounded-2">
                                    {% if profile.profile.birthday %}
                                        <p class="mb-1">{% trans 'birthday' %}: {{ profile.profile.birthday }}</p>
                                    {% endif %}
                                    {% if profile.profile.about %}
                                        <p class="mb-1">{% trans 'about' %}: {{ profile.profile.about }}</p>
                                    {% endif %}
                                </div>
                            </div>
                        {% endif %}
                        {% if quotes %}
                            <div class="d-flex justify-content-between align-items-center mb-4 text-body">
                                <p class="lead fw-normal mb-0">{% trans 'quotes_plural' %}</p>
                                <p class="mb-0"><a href="{% url 'search:by' %}?author={{ profile.pk }}" class="text-muted">{% trans "show_all" %}</a></p>
                            </div>
                            <div class="album py-5">
                                <div class="container">
                                    <div class="row row-cols-auto align-center g-3 justify-content-center d-flex">
                                        {% for quote in quotes %}
                                            {% include 'includes/quotecard.html' %}
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}